server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://localhost/shippings?useUnicode=true&characterEncoding=utf-8
    username: root
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://dmall-shipping-db.cti1pnc10c3g.rds.cn-north-1.amazonaws.com.cn/shippings?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: false
